version: "3"
services:
  blog_webserver:
    image: nginx:alpine
    container_name: "blog_webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf:/etc/nginx/conf.d/
    networks:
      - app-network

  blog_php_app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: "blog_php_app"
    volumes:
      - ./:/var/www
    networks:
      - app-network

  blog_nodejs:
    image: node:alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=debug
    volumes:
      - ./:/home/node/app
    command: npm run watch

networks:
  app-network:
    driver: bridge
